.python-image: &python-image
  image: 'python:3.8'
  before_script:
    - python --version

.node-image: &node-image
  image: 'node'

.selenium-image: &selenium-image
  image: 'registry-gitlab.asynchrony.com/proj-1678/snow-vue'

stages:
  # - test
  # - e2e
  # - backend-deploy-to-dev
  - frontend-deploy-website
  # - deploy-to-prod

# build site:
#   image: node:latest
#   stage: build
#   script:
#     - yarn install --progress=false
#     - yarn run build

# javascript unittest:
#   <<: *node-image
#   tags:
#     - dind
#   stage: test
#   script:
#     - yarn install
#     - cd app
#     - yarn unit

# python unittest:
#   <<: *python-image
#   tags:
#     - dind
#   stage: test
#   script:
#     - cd api
#     - pip3 install boto3
#     - python3 -m unittest discover -p *_test*.py

# e2e:
#   <<: *selenium-image
#   tags:
#     - dind
#   stage: e2e
#   script:
#     - yarn install
#     - yarn e2e
#   variables:
#     HUB_HOST: 'hub'
#     HUB_PORT: 4723
# backend deploy to dev:
#   tags:
#     - dind
#   stage: backend-deploy-to-dev
#   script:
#     - yarn workspace api deploy

frontend-deploy-to-dev:
  <<: *node-image
  tags:
    - dind
  stage: frontend-deploy-website
  only:
    - master
  script:
  - apt-get update
  - apt-get install python3.6
#     - yarn install
#     - yarn build
#     - cd app/www
#     - pwd
#     - yum install -y python36u python36u-libs python36u-devel python36u-pip
#     - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
#     - python get-pip.py
#     - pip install awscli
#     - aws s3 rm s3://mountainweatherreport.net/ --recursive
#     - aws s3 cp ./ s3://mountainweatherreport.net/ --recursive #--exclude "*" --include "*.html"
