---
swagger: "2.0"
info:
  version: "2019-12-16T21:07:07Z"
  title: "test-wwt-snow-vue-python"
host: "4hql04b1p2.execute-api.us-east-1.amazonaws.com"
basePath: "/test"
schemes:
- "https"
paths:
  /traffic:
    get:
      summary: "Retrieve traffic estimate"
      description: "Retrieve traffic estimate from location. Defaults to zipcode 80202"
      produces:
      - "application/json"
      parameters:
      - name: "zipcode"
        in: "query"
        description: "Five digit US zipcode"
        required: false
        type: "string"
      - name: "location"
        in: "query"
        description: "User's five digit zipcode"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/TrafficResponse"
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
        204:
          description: "204 response"
          schema:
            $ref: "#/definitions/TrafficErrorResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /weather:
    get:
      summary: "Retrieve weather information"
      description: "Retrieve weather for particular resort"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/WeatherResponse"
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
        204:
          description: "204 response"
          schema:
            $ref: "#/definitions/WeatherErrorResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  WeatherErrorResponse:
    type: "object"
    properties:
      status_code:
        type: "integer"
      message:
        type: "string"
    description: "Error for weather data"
  WeatherResponse:
    type: "object"
    properties:
      inches:
        type: "string"
      cm:
        type: "string"
      timestamp:
        type: "string"
    description: "Model for weather data"
  TrafficResponse:
    type: "object"
    properties:
      TrafficReport:
        type: "object"
        properties:
          start_location:
            type: "string"
          destination:
            type: "string"
          travel_time:
            type: "object"
            properties:
              hour:
                type: "string"
              minute:
                type: "string"
    description: "Model for the traffic response"
  TrafficErrorResponse:
    type: "object"
    properties:
      status_code:
        type: "integer"
      message:
        type: "string"
    description: "Model for the traffic error response"
  ErrorResponse:
    type: "object"
    properties:
      status_code:
        type: "integer"
      message:
        type: "string"
    description: "This is an error"
