service: wwt-snow-vue-python
provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  deploymentBucket:
    name: wwt-snow-vue-deploy
package:
  individually: true
  exclude:
    - package-lock.json
    - package.json
    - README.md
    - weather/keystone_weather_test.py
    - swagger.yml
    - config.py
    - __init__.py
custom:
  defaultStage: dev
  profiles:
    dev: dev
    prod: prod
  documentation:
    models:
      - name: 'ErrorResponse'
        description: 'This is an error'
        contentType: 'application/json'
      - name: 'TrafficResponse'
        description: 'Model for the traffic response'
        contentType: 'application/json'
        schema:
          type: 'object'
          properties:
            hour:
              type: 'string'
            minute:
              type: 'string'
      - name: 'TrafficErrorResponse'
        description: 'Model for the traffic error response'
        contentType: 'application/json'
        schema:
          type: 'object'
          properties:
            status_code:
              type: 'int'
            message:
              type: 'string'
      - name: 'WeatherError'
        description: 'Error for weather data'
        contentType: 'application/json'
      - name: 'WeatherResponse'
        description: 'Model for weather data'
        contentType: 'application/json'
        schema:
          type: 'object'
          properties:
            inches:
              type: 'string'
            cm:
              type: 'string'
            timestamp:
              type: 'string'
functions:
  weather:
    handler: weather/weather_handler.weatherHandler
    events:
      - http:
          path: weather
          cors: true
          method: get
          documentation:
            summary: 'Retrieve weather information'
            description: 'Retrieve weather for particular resort'
    package:
      exclude:
        - traffic/**
    role: arn:aws:iam::963760208122:role/lambda_cli_role
  traffic:
    handler: traffic/traffic_handler.trafficHandler
    events:
      - http:
          method: get
          path: traffic
          documentation:
            summary: 'Retrieve traffic estimate'
            description: 'Retrieve traffic estimate from location. Defaults to zipcode 80202'
            queryParams:
              - name: 'zipcode'
                description: 'Five digit US zipcode'
              - name: 'location'
                description: "User's US address"
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'Return travel duration with timestamp or error status code with custom error message'
                responseModels:
                  'application/json': 'TravelResponse'
              - statusCode: '400'
                responseModels:
                  'application/json': 'ErrorResponse'

    package:
      exclude:
        - weather/**
    role: arn:aws:iam::963760208122:role/lambda_cli_role
