service: snowballers
provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
package:
  individually: true
  exclude:
    - package-lock.json
    - package.json
    - README.md
    - weather/keystone_weather_test.py
    - swagger.yml
    - config.py
    - __init__.py
custom:
  defaultStage: dev
  profiles:
    dev: dev
    prod: prod
functions:
  weather:
    handler: weather/weather_handler.weatherHandler
    events:
      - http:
          path: weather
          method: get
    package:
      exclude:
        - traffic/**
