swagger: "2.0"
info:
  description: "Ski Resort Info API"
  version: "1.0.0"
  title: "Resorts"
host: "aws.apigateway.placeholder"
basePath: "/"
tags:
- name: "keystone"
  description: "Everything about keystone"
schemes:
- "https"
paths:
  /keystone:
    get:
      tags:
      - "keystone"
      summary: "Get weather and travel info for keystone"
      operationId: "getKeystone"
      consumes:
      - "path"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "userLocation"
        description: "user location to be passed to google location API"
        required: false
        type: string
      responses:
        200:
          schema:
            $ref: "#/definitions/KeystoneReport"
          description: "Available reports for keystone"
        503:
          description: "Unavailable"
definitions:
  KeystoneReport:
    type: "object"
    properties:
      SnowReport:
        type: "string"
      TravelTime:
        type: "string"
        format: "hh:mm:ss"